source "http://rubygems.org"

gem "rails", "3.0.0.rc"
gem "pg", "0.9.0"
gem "rdiscount", "1.6.5"
gem "will_paginate", "3.0.pre2"
gem "compass", "0.10.2"
gem "memcache-client", "1.8.5"
gem "memcached-northscale", "0.19.5.3", :require => "memcached"
gem "hoptoad_notifier", "2.3.2"
