source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'pg', '0.9.0'
gem 'rdiscount', '1.6.5'
gem 'will_paginate', '3.0.pre2'
gem 'compass', '0.10.5'
gem 'system_timer', '1.0'
gem 'hoptoad_notifier', '2.3.6'
gem 'tweet-button', '0.1.0'
gem 'goalie', '0.0.2'
gem 'xmlrpc-endpoint', :git => 'http://github.com/samsoffes/xmlrpc-endpoint.git'
gem 'memcache-client', '1.8.5'
gem 'memcached-northscale', '0.19.5.3', :require => 'memcached'
