ADMIN_USERNAME = (ENV['ADMIN_USERNAME'] or "admin")
ADMIN_PASSWORD = (ENV['ADMIN_PASSWORD'] or "passw0rd")

LAST_FM_USERNAME = "samsoffes"
LAST_FM_API_KEY = (ENV['LAST_FM_API_KEY'] or "b25b959554ed76058ac220b7b2e0a026")
LAST_FM_API_SECRET = (ENV['LAST_FM_API_SECRET'] or nil)

TWITTER_ANYWHERE_API_KEY = "ZUgEyEcINKMBQNJzqcfMiw"

GOOGLE_ANALYTICS_KEY = "UA-5609322-1"
OBSERVER_APP_KEY = "agtvYnNlcnZlcmFwcHINCxIEU2l0ZRjkyvUBDA"
